export default {
  nodes: [
    // One
    {
      id: 'Hero 01 A',
      name: 'Hero 01 A',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01a.png',
    },
    {
      id: 'Hero 01 AA',
      name: 'Hero 01 AA',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01a.png',
    },
    {
      id: 'Hero 01 AAA',
      name: 'Hero 01 AAA',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01a.png',
    },
    {
      id: 'Hero 01 B',
      name: 'Hero 01 B',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01b.png',
    },
    {
      id: 'Hero 01 BB',
      name: 'Hero 01 BB',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01b.png',
    },
    {
      id: 'Hero 01 BBB',
      name: 'Hero 01 BBB',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01b.png',
    },
    {
      id: 'Hero 01 C',

      name: 'Hero 01 C',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01c.png',
    },
    {
      id: 'Hero 01 CC',
      name: 'Hero 01 CC',
      color: '#2BACE2 ',
      visible: true,
      image: 'images/mem_hero_01c.png',
    },
    {
      id: 'Hero 01 Empty',
      name: 'Hero 01 Empty',
      color: '#2BACE2 ',
      visible: false,
      image: 'images/mem_hero_01c.png',
    },
    // Two
    {
      id: 'Hero 02 Empty',
      name: 'Hero 02 Empty',
      color: '#45B763 ',
      visible: false,
      image: 'images/mem_hero_02a.png',
    },
    {
      id: 'Hero 02 A',
      name: 'Hero 02 A',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02a.png',
    },
    {
      id: 'Hero 02 B',
      name: 'Hero 02 B',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02b.png',
    },
    {
      id: 'Hero 02 C',
      name: 'Hero 02 C',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02c.png',
    },
    {
      id: 'Hero 02 AA',
      name: 'Hero 02 A',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02a.png',
    },
    {
      id: 'Hero 02 BB',
      name: 'Hero 02 B',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02b.png',
    },
    {
      id: 'Hero 02 CC',
      name: 'Hero 02 C',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02c.png',
    },
    {
      id: 'Hero 02 AAA',
      name: 'Hero 02 A',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02a.png',
    },
    {
      id: 'Hero 02 BBB',
      name: 'Hero 02 B',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02b.png',
    },
    {
      id: 'Hero 02 CCC',
      name: 'Hero 02 C',
      color: '#45B763 ',
      visible: true,
      image: 'images/mem_hero_02c.png',
    },
    // Three
    {
      id: 'Hero 03 A',

      name: 'Hero 03 A',
      color: '#7989FF ',
      visible: true,
      image: 'images/mem_hero_03a.png',
    },
    {
      id: 'Hero 03 B',

      name: 'Hero 03 B',
      color: '#7989FF ',
      visible: true,
      image: 'images/mem_hero_03b.png',
    },
    {
      id: 'Hero 03 C',

      name: 'Hero 03 C',
      color: '#7989FF ',
      visible: true,
      image: 'images/mem_hero_03c.png',
    },
    // Four
    {
      id: 'Hero 04 A',

      name: 'Hero 04 A',
      color: '#EA797E ',
      visible: true,
      image: 'images/mem_hero_04a.png',
    },
    {
      id: 'Hero 04 B',

      name: 'Hero 04 B',
      color: '#EA797E ',
      visible: true,
      image: 'images/mem_hero_04b.png',
    },
    {
      id: 'Hero 04 C',

      name: 'Hero 04 C',
      color: '#EA797E ',
      visible: true,
      image: 'images/mem_hero_04c.png',
    },
    // Five
    {
      id: 'Hero 05 A',

      name: 'Hero 05 A',
      color: '#FAC915 ',
      visible: true,
      image: 'images/mem_hero_05a.png',
    },
    {
      id: 'Hero 05 B',

      name: 'Hero 05 B',
      color: '#FAC915',
      visible: true,
      image: 'images/mem_hero_05b.png',
    },
    {
      id: 'Hero 05 C',

      name: 'Hero 05 C',
      color: '#FAC915 ',
      visible: true,
      image: 'images/mem_hero_05c.png',
    },
  ],

  links: [
    {
      source: 'Hero 01 A',
      target: 'Hero 01 B',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 01 A',
      target: 'Hero 01 C',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 01 B',
      target: 'Hero 01 C',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 01 A',
      target: 'Hero 01 B',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 01 A',
      target: 'Hero 01 C',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 01 AA',
      target: 'Hero 01 BB',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 0.5,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 01 AA',
      target: 'Hero 01 BB',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 1,
      visible: true,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 01 Empty',
      target: 'Hero 01 BB',
      //length
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 01 Empty',
      target: 'Hero 01 CC',
      //length
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 01 Empty',
      target: 'Hero 01 A',
      //length
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 01 Empty',
      target: 'Hero 01 AAA',
      //length
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 01 Empty',
      target: 'Hero 01 BBB',
      //length
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 01 B',
      target: 'Hero 01 C',
      //length
      value: 1,
      color: '#2BACE2 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 02 A',
      target: 'Hero 02 B',
      //length
      value: 1,
      color: '#45B763 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 02 A',
      target: 'Hero 02 C',
      value: 1,
      color: '#45B763 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 02 Empty',
      target: 'Hero 02 A',
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 Empty',
      target: 'Hero 02 BBB',
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 Empty',
      target: 'Hero 02 CCC',
      //length
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 Empty',
      target: 'Hero 02 AA',
      visible: false,
      value: 1,
      color: '#45B763 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 Empty',
      target: 'Hero 02 BB',
      visible: false,
      value: 1,
      color: '#45B763 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 AA',
      target: 'Hero 02 BB',
      visible: true,
      value: 1,
      color: '#45B763 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 AA',
      target: 'Hero 02 BB',
      visible: true,
      value: 1,
      color: '#45B763 ',
      curve: 0.3,
      rotation: Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 Empty',
      target: 'Hero 02 CC',
      visible: false,
      value: 1,
      color: '#45B763 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 Empty',
      target: 'Hero 02 AAA',
      //length
      visible: false,
      value: 1,
      color: '#2BACE2 ',
      curve: 0.3,
      rotation: -Math.PI * (2 / 6),
    },
    {
      source: 'Hero 02 B',
      target: 'Hero 02 C',
      //length
      value: 1,
      color: '#45B763 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 03 A',
      target: 'Hero 03 B',
      //length
      value: 1,
      color: '#7989FF ',
      curve: 0,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 03 A',
      target: 'Hero 03 C',
      //length
      value: 1,
      color: '#7989FF ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 03 B',
      target: 'Hero 03 C',
      //length
      value: 1,
      color: '#7989FF ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 04 A',
      target: 'Hero 04 B',
      //length
      value: 1,
      color: '#EA797E ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 04 A',
      target: 'Hero 04 C',
      //length
      value: 1,
      color: '#EA797E ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 04 B',
      target: 'Hero 04 C',
      //length
      value: 1,
      color: '#EA797E ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 05 A',
      target: 'Hero 05 B',
      //length
      value: 1,
      color: '#FAC915 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 05 A',
      target: 'Hero 05 C',
      //length
      value: 1,
      color: '#FAC915 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
    {
      source: 'Hero 05 B',
      target: 'Hero 05 C',
      //length
      value: 1,
      color: '#FAC915 ',
      curve: 0,
      visible: true,
      rotation: -Math.PI * (10 / 6),
    },
  ],
}
